build:
    tests:
        override:
            -
                command: './vendor/bin/phpunit --coverage-clover=coverage.clover'
                coverage:
                    file:   'coverage.clover'
                    format: 'php-clover'
checks:
    php:
        code_rating: true
